version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farm_db
    volumes:
      - ./src/main/resources/db/migration/init.sql:/docker-entrypoint-initdb.d/init.sql

